name: Release Drafter

on:
  push:
    branches: 
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          commitish: main # https://github.com/release-drafter/release-drafter/issues/1125#issuecomment-1471142225
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
